export const INITIAL_CATEGORIES = [
  { id: "all", name: "جميع المنتجات", icon: "fa-cubes" },
  { id: "memorial-shields", name: "دروع تذكارية", icon: "fa-trophy" },
  { id: "flags", name: "الأعلام", icon: "fa-flag" },
  { id: "certificates", name: "شهادات تقدير", icon: "fa-certificate" },
  { id: "cutting", name: "قص وتقطيع", icon: "fa-scissors" },
  { id: "honor-shields", name: "دروع تكريم", icon: "fa-award" },
  { id: "uniforms", name: "اليونيفورم", icon: "fa-shirt" },
  { id: "mugs-gifts", name: "المجات والهدايا", icon: "fa-mug-hot" },
  { id: "cards-prints", name: "كروت ومطبوعات", icon: "fa-id-card" },
  { id: "logos-ads", name: "لوجوهات وإعلانات", icon: "fa-bullhorn" },
  { id: "serials-stamps", name: "السريلات والأختام", icon: "fa-stamp" }
];

export const INITIAL_PRODUCTS = [
  {
    id: "prod-cert-01",
    name: "شهادة تقدير كوشيه فاخرة مع غلاف جلدي مذهب",
    category: "certificates",
    retailPrice: 45,
    wholesalePrice: 28,
    stock: 120,
    unit: "قطعة",
    description: "ورق كوشيه 350 جرام مع بصمة ذهبية حرارية، غلاف كرتوني فاخر مبطن بالجلد الأسود أو الكحلي.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "اكتب الاسم والجهة ونص الإهداء المطلوب طباعته",
    allowImageUpload: true,
    badge: "الأكثر طلباً",
    featured: true
  },
  {
    id: "prod-cert-02",
    name: "شهادة تخرج كرتونية مقواة مع إطار خشبي أنيق",
    category: "certificates",
    retailPrice: 75,
    wholesalePrice: 50,
    stock: 85,
    unit: "قطعة",
    description: "طباعة ديجيتال فائقة الدقة بالألوان الكاملة مع برواز خشب طبيعي بواجهة زجاجية ضد الانعكاس.",
    image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "بيانات الخريج والتخصص وسنة التخرج",
    allowImageUpload: true,
    badge: "مميز",
    featured: true
  },
  {
    id: "prod-shield-01",
    name: "درع كريستال شرفي محفور بالليزر مع علبة قطيفة",
    category: "shields",
    retailPrice: 190,
    wholesalePrice: 135,
    stock: 45,
    unit: "قطعة",
    description: "كريستال K9 نقي عالي البريق، حفر ليزر ثلاثي الأبعاد أو طباعة UV ملونة مقاومة للخدش.",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "نص التكريم واسم المكرّم وشعار المؤسسة",
    allowImageUpload: true,
    badge: "فخامة",
    featured: true
  },
  {
    id: "prod-shield-02",
    name: "درع خشبي فاخر مطعم بالنحاس المطلي بالذهب",
    category: "shields",
    retailPrice: 220,
    wholesalePrice: 160,
    stock: 30,
    unit: "قطعة",
    description: "خشب زان طبيعي بتشطيب ملكي مع صفيحة نحاسية محفورة ومطلية بجودة تدوم لسنوات.",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "نص الإهداء واسم الشخص أو الهيئة المكرمة",
    allowImageUpload: true,
    badge: "حصري",
    featured: false
  },
  {
    id: "prod-banner-01",
    name: "يافطة بنر خارجي فليكس مقوى مقاوم للشمس والمطر (بالمتر)",
    category: "banners",
    retailPrice: 110,
    wholesalePrice: 75,
    stock: 250,
    unit: "متر مربع",
    description: "خامة فليكس عالية الكثافة 510 جرام، طباعة يابانية بالأحبار المذيبة المانعة للتلاشي مع حلقات تعليق معدنية.",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "المقاسات بالمتر والنص الرئيسي والإعلاني المطلوب",
    allowImageUpload: true,
    badge: "ضمان أحبار",
    featured: true
  },
  {
    id: "prod-banner-02",
    name: "رول اب ستاند إعلاني متحرك مقاس 85×200 سم",
    category: "banners",
    retailPrice: 380,
    wholesalePrice: 290,
    stock: 40,
    unit: "ستاند كامل",
    description: "هيكل ألومنيوم ثقيل مع طباعة سلوفان غير عاكسة وحقيبة قماشية مبطنة للحمل والتنقل في المعارض والمؤتمرات.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "محتوى الإعلان والبيانات والألوان المقترحة",
    allowImageUpload: true,
    badge: "الأكثر مبيعاً",
    featured: true
  },
  {
    id: "prod-tshirt-01",
    name: "تيشرت قطن 100% مع طباعة DTF حرارية ملونة وثابتة",
    category: "tshirts",
    retailPrice: 130,
    wholesalePrice: 85,
    stock: 180,
    unit: "قطعة",
    description: "قطن ميلتون مصري فائق النعومة، طباعة DTF عالية الثبات تقاوم الغسيل المتكرر دون بهتان أو تشقق.",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "المقاس (S, M, L, XL, XXL)، اللون ومكان الطباعة (صدر/ظهر)",
    allowImageUpload: true,
    badge: "قطن 100%",
    featured: true
  },
  {
    id: "prod-mug-01",
    name: "مج سحري حراري مع طباعة سبلميشن بالصورة والاسم",
    category: "mugs",
    retailPrice: 65,
    wholesalePrice: 40,
    stock: 150,
    unit: "قطعة",
    description: "مج سيراميك أسود يتغير لونه ويظهر الصورة والتصميم بوضوح مدهش عند سكب المشروبات الساخنة.",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "الاسم أو العبارة التذكارية المكتوبة",
    allowImageUpload: true,
    badge: "هدايا",
    featured: true
  },
  {
    id: "prod-mug-02",
    name: "مج أبيض كلاسيكي بطباعة شعار أو صورة بجودة فوتوغرافية",
    category: "mugs",
    retailPrice: 45,
    wholesalePrice: 28,
    stock: 200,
    unit: "قطعة",
    description: "سيراميك براق عالي الجودة آمن للاستخدام في الميكروويف وغسالة الأطباق.",
    image: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "نص الإهداء أو الشعار",
    allowImageUpload: true,
    badge: "كميات للمؤسسات",
    featured: false
  },
  {
    id: "prod-card-01",
    name: "كروت شخصية بيزنس كارد فاخرة (1000 كارت سلوفان مطفي)",
    category: "cards",
    retailPrice: 180,
    wholesalePrice: 125,
    stock: 90,
    unit: "علبة 1000 كارت",
    description: "ورق كوشيه 350 جرام، طباعة وجهين بألوان دقيقة مع طبقة سلوفان غير لامع وزوايا دائرية أو مستقيمة.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80",
    allowCustomText: true,
    customTextPlaceholder: "الاسم، المسمى الوظيفي، أرقام الهاتف، العناوين وروابط التواصل",
    allowImageUpload: true,
    badge: "عرض 1000 كارت",
    featured: true
  }
];
